AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  drs-sfn-orchestrator

  DRS orchestrator function, launching recovery instances by wave tag thru Step Functions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.10
    Handler: app.handler
    Timeout: 20
    Tracing: Active
    Architectures:
        - arm64
    Environment:
      Variables:
        LOG_LEVEL: DEBUG

Resources:
  OrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/orchestrator/
      Handler: app.lambda_handler
      Policies:
        - Statement: 
          - Sid: OrachestratorFunctionPolicy
            Action:
            - ec2:AttachVolume
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:DeleteSnapshot
            - ec2:DescribeInstances
            - ec2:DescribeInstanceAttribute
            - ec2:DescribeSnapshots
            - drs:TagResource
            - ec2:DeleteVolume
            - iam:PassRole
            - drs:StartRecovery
            - drs:DescribeJobs
            - ec2:StartInstances
            - ec2:DescribeAvailabilityZones
            - ec2:RevokeSecurityGroupEgress
            - ec2:DescribeVolumes
            - ec2:CreateSnapshot
            - ec2:DescribeAccountAttributes
            - ec2:DeleteLaunchTemplateVersions
            - ec2:ModifyInstanceAttribute
            - ec2:DescribeInstanceStatus
            - ec2:DetachVolume
            - ec2:AuthorizeSecurityGroupEgress
            - drs:UntagResource
            - ec2:TerminateInstances
            - drs:DescribeSourceServers
            - ec2:DescribeLaunchTemplates
            - drs:ListTagsForResource
            - ec2:CreateTags
            - ec2:DescribeLaunchTemplateVersions
            - ec2:RunInstances
            - drs:DescribeJobLogItems
            - ec2:StopInstances
            - ec2:DescribeSecurityGroups
            - ec2:CreateLaunchTemplateVersion
            - ec2:CreateVolume
            - ec2:DescribeImages
            - ec2:CreateLaunchTemplate
            - drs:CreateRecoveryInstanceForDrs
            - ec2:DescribeInstanceTypes
            - ec2:ModifyLaunchTemplate
            - ec2:DescribeSubnets
            Effect: Allow
            Resource: "*"

  OrchestratorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/orchestrator.asl.yaml
      DefinitionSubstitutions:
        OrchestratorFunctionArn: !GetAtt OrchestratorFunction.Arn
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !GetAtt OrchestratorFunction.Arn
  
  #Lambda to control state machine initialization
  StateMachineControllerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stateMachineController/
      Handler: app.lambda_handler
      Policies:
        - Statement: 
          - Sid: AllowLambdaCallStateMachine
            Action:
            - states:ListExecutions
            - states:StartExecution
            Effect: Allow
            Resource: !GetAtt OrchestratorStateMachine.Arn
      Environment:
        Variables:
          STATEMACHINE_ARN: !GetAtt OrchestratorStateMachine.Arn
      Events:
        StateMachineControllerApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /start
            Method: post

  # #API
  # #role to invoke state machine
  # ApiGatewayToStepFunctionRole:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: "Allow"
  #           Principal:
  #             Service: "apigateway.amazonaws.com"
  #           Action: 
  #             - "sts:AssumeRole"
  #     Policies:
  #       - PolicyName: ApiDirectInvokeStepFunction
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             Action:
  #             - "states:ListStateMachines",
  #             - "states:ListActivities",
  #             - "states:ListExecutions",
  #             - "states:StartExecution"
  #             Effect: Allow
  #             Resource:
  #               - !Ref OrchestratorStateMachine